model_args:
  backbone: terramind_v1_base
  backbone_ckpt_path: ./src/ckpt/TerraMind_v1_base.pt
  backbone_img_size: 224
  backbone_in_chans: 12
  backbone_modalities:
  - S2L2A
  backbone_bands:
    S2L2A:
    - COASTAL_AEROSOL
    - BLUE
    - GREEN
    - RED
    - RED_EDGE_1
    - RED_EDGE_2
    - RED_EDGE_3
    - NIR_BROAD
    - NIR_NARROW
    - WATER_VAPOR
    - SWIR_1
    - SWIR_2
  necks:
  - name: SelectIndices
    indices:
    - -1
  - name: ReshapeTokensToImage
    remove_cls_token: false
  decoder: FCNDecoder
  decoder_channels: 256
  head_dropout: 0.21
  num_classes: 11
model_factory: EncoderDecoderFactory
model: null
loss: ce
aux_heads: null
aux_loss: null
class_weights: null
ignore_index: -100
lr: 0.001
optimizer: null
optimizer_hparams: null
scheduler: null
scheduler_hparams: null
freeze_backbone: false
freeze_decoder: false
freeze_head: false
plot_on_val: 10
class_names:
- Dense forest
- Light forest
- Forest Gallery
- Forest plantation
- Rubber plantation
- Cashew plantation
- Agricultural area
- Tree savannah
- Human habitat
- Background
tiled_inference_parameters: null
test_dataloaders_names: null
lr_overrides: null
output_on_inference: prediction
output_most_probable: true
path_to_record_metrics: ./outputs/enmap_bnetd/
tiled_inference_on_testing: false
tiled_inference_on_validation: false
_instantiator: lightning.pytorch.cli.instantiate_module
