# @package _global_

defaults:
  - _self_
  - data: null
  - model: null
  - trainer: default  
  - paths: default
  - optimizer: adamw_standard
  - scheduler: cosine_annealing
  - logger: wandb
  - callbacks: default
  - experiment: null

task_name: null

ckpt_root: null

seed_everything: 42

train: true

test: false